version: '3.5'
name: pokeshop

services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ashketchum
      POSTGRES_PASSWORD: squirtle123
      POSTGRES_DB: pokeshop
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 1s
      timeout: 5s
      retries: 60
